<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ProBook" failures="1" tests="3" name="Test" time="15.516" errors="0" timestamp="2021-10-06T00:26:00 EDT">
  <testcase classname="framework.RediffTest" name="rediffTester" time="5.687"/>
  <testcase classname="framework.RediffTest" name="rediffTester" time="5.93"/>
  <testcase classname="framework.Validator" name="getValidate" time="0.154">
    <failure type="java.lang.AssertionError" message="expected [Rediff.com: News | Rediffmail | Stock Quotes | Shopping] but found [Rediff.com: News | Rediffmail | Stock Quotes | Shoppin]">
      <![CDATA[java.lang.AssertionError: expected [Rediff.com: News | Rediffmail | Stock Quotes | Shopping] but found [Rediff.com: News | Rediffmail | Stock Quotes | Shoppin]
at framework.Validator.getValidate(Validator.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- getValidate -->
</testsuite> <!-- Test -->
