<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-06T00:25:45 EDT" name="Suite" finished-at="2021-10-06T00:26:00 EDT" duration-ms="15516">
    <groups>
    </groups>
    <test started-at="2021-10-06T00:25:45 EDT" name="Test" finished-at="2021-10-06T00:26:00 EDT" duration-ms="15516">
      <class name="framework.RediffTest">
        <test-method signature="rediffTester(java.lang.String,java.lang.String)[pri:0, instance:framework.RediffTest@6babf3bf]" started-at="2021-10-06T00:25:48 EDT" name="rediffTester" data-provider="getLoginInfo" finished-at="2021-10-06T00:25:53 EDT" duration-ms="5687" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hello@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abcdef]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rediffTester -->
        <test-method signature="rediffTester(java.lang.String,java.lang.String)[pri:0, instance:framework.RediffTest@6babf3bf]" started-at="2021-10-06T00:25:53 EDT" name="rediffTester" data-provider="getLoginInfo" finished-at="2021-10-06T00:25:59 EDT" duration-ms="5930" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[john@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rediffTester -->
      </class> <!-- framework.RediffTest -->
      <class name="framework.Validator">
        <test-method is-config="true" signature="initialize()[pri:0, instance:framework.Validator@6da21078]" started-at="2021-10-06T00:25:45 EDT" name="initialize" finished-at="2021-10-06T00:25:48 EDT" duration-ms="3192" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="getValidate()[pri:0, instance:framework.Validator@6da21078]" started-at="2021-10-06T00:25:59 EDT" name="getValidate" finished-at="2021-10-06T00:26:00 EDT" duration-ms="154" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Rediff.com: News | Rediffmail | Stock Quotes | Shopping] but found [Rediff.com: News | Rediffmail | Stock Quotes | Shoppin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Rediff.com: News | Rediffmail | Stock Quotes | Shopping] but found [Rediff.com: News | Rediffmail | Stock Quotes | Shoppin]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at framework.Validator.getValidate(Validator.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getValidate -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:framework.Validator@6da21078]" started-at="2021-10-06T00:26:00 EDT" name="closeBrowser" finished-at="2021-10-06T00:26:00 EDT" duration-ms="200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- framework.Validator -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
